---
- hosts: all
  gather_facts: false
  vars:
    dest_dir: /var/www/reward-chart
    debug: true
  tasks:
    - name: Upload project
      ansible.posix.synchronize:
        src: "{{ item }}"
        dest: "{{ dest_dir }}"
      with_items:
        - ../reward_chart
        - ../requirements.txt
      when: not debug
    - name: PIP install
      ansible.builtin.pip:
        virtualenv: "{{ dest_dir }}/.venv"
        requirements: "{{dest_dir}}/requirements.txt"
        virtualenv_command: python3 -m venv
