---
- hosts: all
  gather_facts: false
  tasks:
    - name: Installing required packages
      ansible.builtin.apt:
        pkg:
          - python3-dev
          - python3-venv
          - default-libmysqlclient-dev
          - build-essential
          - libpq-dev
